from collections import deque
q = deque()
print(q)
q.appendleft(10)
q.appendleft(20)
q.appendleft(30)
print(q)
print(q.pop())
print(q.pop())
print(q.pop())
print(q)
q.append(70)
q.append(58)
q.append(87)
print(q.popleft())
print(q.popleft())
print(q.popleft())
print(q)
